### ISSUE TITLE
Ctrl-S & Ctrl-Ent are browser dependent

### ISSUE THREAD

**Issue by brontidebrontide** [captainwasabi/topologrjs#18]
Ctrl-S (for save) and Ctrl-Ent (for new random diagram) give inconsistent results depending on browser used.  _Brave_ works fine, _Waterfox_ and _Firefox_ have issues.  Instead of such hidden options, a menu for such options that may avoid the inconsistencies among different browsers.

**Comment by captainwasabi** [comment]
I could not reproduce this.  Things to look for: 1) set Thunderbird to always Save As... and 2) always click in the inside of the network panel before entering the keyboard command.

I'm going to redo the front end using css grid.  This will let me easily leave space for buttons and more information at the top and bottom of the page.  It looks really easy (a phase which fits in the same category as "Hey, I think we're out of gas but I can't see down in the tank, got a match?)

**Comment by brontidebrontide** [comment]
I tested again:

- _Brave browser_ - still good.

- _Waterfox_ - now good (don't know what changed). 

- _Vivaldi_ - good

- _Firefox_ is weird: When I hit Ctrl-s once it performs the action to show menu of recent downloads.  Hit Ctrl-s a second time and it goes to "save-as" the "xxx Mesh Network.htm".

(I think when you referred to Thunderbird ..save-as.. you meant the browser... I closed Thunderbird anyway but as expected that made no difference.)

It's not really an issue for me as I use Brave for this anyway.  :)
Happy Camper :)

**Comment by captainwasabi** [comment]
looks like you have to make sure to click into the background again after that first save in Firefox.  I I think the website loses focus when the download file dialog come up

**Comment by brontidebrontide** [comment]
Well I found the problem...Maybe I have too many browsers!  Sure enough the problem was it was automatically downloading "Always ask you where to save files" was **not** selected!!  geez...  Okay, all browsers are okay...no problem...close issue!  Thanks!
